name: Blockscout Docs

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - master

jobs:
  cspell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v6
        with:
          use_cspell_files: true
          incremental_files_only: false